import { Roboto } from 'next/font/google';
import Topbar from '@/components/layout/Topbar';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import './globals.css';
import './styles/css/bootstrap.min.css';
import './styles/css/custom.css';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Research Proposal',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Topbar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
