/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-css-tags */
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/layout/Topbar";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Research Porposal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    {/* <link rel="icon" type="image/svg+xml" href="" /> */}
    {/* <link rel="shortcut icon" type="image/x-icon" href="/assets/images/icon.png" /> */}
    <link rel="preconnect" href="https://fonts.googleapis.com/" />
    {/* <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin /> */}
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&amp;display=swap"rel="stylesheet"/>
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" media="screen" />
    {/* <link href="/assets/css/slicknav.min.css" rel="stylesheet" /> */}
    <link rel="stylesheet" href="/assets/css/swiper-bundle.min.css" />
    <link href="/assets/css/all.min.css" rel="stylesheet" media="screen" />
    <link href="/assets/css/animate.css" rel="stylesheet" />
    {/* <link rel="stylesheet" href="/assets/css/magnific-popup.css" /> */}
    {/* <link rel="stylesheet" href="/assets/css/mousecursor.css" /> */}
    <link href="/assets/css/custom.css" rel="stylesheet" media="screen" />
  </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Topbar/>
      <Header/>
        {children}
         <Footer />
      </body>
    </html>
  );
}
